apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
spec:
  replicas: 1
  selector:
    # matchLabels:
    #   app: second-app
    #   tier: backend
    matchExpressions:
      - {key: app, operator: In, values: [second-app, first-app]}
        operator: 
  template:
    metadata:
      labels:
        app: second-app
        tier: backend
    spec:
      containers:
        - name: second-node
          image: tobsirl/kub-first-app:3
          # ports:
          #   - containerPort: 80
