apiVersion: v1
kind: Pod
metadata:
  labels:
    run: logger
  name: logger
spec:
  containers:
  - image: nginx:alpine
    name: logger
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
