apiVersion: v1
kind: Pod
metadata:
  labels:
    run: port-pod
  name: port-pod
spec:
  containers:
  - image: nginx
    name: port-pod
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
